const ConstantScreen = {
  SUPPORTSCREEN: 'SUPPORTSCREEN',
  SETTINGSSCREEN: 'SETTINGSSCREEN',
  BOOKMARKSCREEN: 'BOOKMARKSCREEN',
  HOMESCREEN: 'HOMESCREEN',
  DETAILSCREEN: 'DETAILSCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  EXPLORESCREEN: 'EXPLORESCREEN',
  NOTIFCATIONSCREEN: 'NOTIFCATIONSCREEN',
  MAPSCREEN: 'MAPSCREEN',
};
const ConstantDrawer = {
  HOMEDRAWER: 'HOMEDRAWER',
};
const ConstantStack = {
  HOMESTACK: 'HOMESTACK',
  NOTIFICATIONSTACK: 'NOTIFICATIONSTACK',
  PROFILESTACK: 'PROFILESTACK',
  EXPLORESTACK: 'EXPLORESTACK',
};
export {ConstantScreen, ConstantDrawer, ConstantStack};
