const ConstantScreen = {
  SUPPORTSCREEN: 'SUPPORTSCREEN',
  SETTINGSSCREEN: 'SETTINGSSCREEN',
  BOOKMARKSCREEN: 'BOOKMARKSCREEN',
  HOMESCREEN: 'HOMESCREEN',
  PERSONLIVESCREEN: 'PERSONLIVESCREEN',
  DETAILSCREEN: 'DETAILSCREEN',
  NOTIFYSCREEN:'NOTIFYSCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  EXPLORESCREEN: 'EXPLORESCREEN',
  SPLASHSCREEN: 'SPLASHSCREEN',
  SIGNINSCREEN: 'SIGNINSCREEN',
  SIGNUPSCREEN: 'SIGNUPSCREEN',
};
const ConstantDrawer = {
  HOMEDRAWER: 'HOMEDRAWER',
};
const ConstantStack = {
  HOMESTACK: 'HOMESTACK',
  NOTIFICATIONSTACK: 'NOTIFICATIONSTACK',
  PROFILESTACK: 'PROFILESTACK',
  EXPLORESTACK: 'EXPLORESTACK',
};
export {ConstantScreen, ConstantDrawer, ConstantStack};
