const NameScreen:any = {
    LoginScreen:"LoginScreen",
    OnboardingScreen:"OnboardingScreen",
    StacksScreen:{
        TabBarBottom:"TabBarBottom",
        NewsStack:"NewsStack",
        AppStack:"AppStack",
        WarningStack:"WarningStack",
        DashboardStack:"DashboardStack",
    },
    DrawerScreen:{
        DashboardScreen:"Thống kê",
        ResponseScreen:"Phản ứng",
        WarningScreen:"Cảnh báo",
        NewsScreen:"Tin tức",
        ContactScreen:"Liên hệ"
    },
    DashBoardScreen:"DashboardScreen",
    NetWorkScreen:"NetWorkScreen",
    HostingScreen:"HostingScreen",
    EndpointScreen:"EndpointScreen",
    ApplicationScreen:"ApplicationScreen",
    StatisticScreen:"StatisticScreen",
    DetailWarningScreen:"DetailWarningScreen",
    WarningScreen:"WarningScreen",
    ResponseScreen:"ResponseScreen",
    NewsScreen:"NewsScreen",
    ContactScreen:"ContactScreen",
    HomeScreen:"HomeScreen",
    GameDetailsScreen:"GameDetailsScreen",
    CartScreen:"CartScreen",
    FavoriteScreen:"FavoriteScreen",
    InfoWarningScreen:"InfoWarningScreen",
    WarningTabs:{
        InForDetailTab:"InForDetailTab",
        InForPolicyTab:"InForPolicyTab",
        InfoProcessTab:"InfoProcessTab",
    },
    DetailNetworkScreen:"DetailNetworkScreen",
    DashboardElementaryScreen:"DashboardElementaryScreen",
    DashboardHightScreen:"DashboardHightScreen",
    DashboardUniversityScreen:"DashboardUniversityScreen",
    NotFoundScreen:"NotFoundScreen",
}
export default NameScreen;