const wordApp = {
    nameApp: 'TRỰC VĂN PHÒNG',
    username: 'Username',
    password: 'Password',
    remember: 'Remember Account',
    login: 'Bắt đầu',
    refresh:'Làm mới',
    number:"Số lượng",
    status:"Trạng thái",
    description:"Phần mềm trực do GIẢI PHÁP TRỰC VĂN PHÒNG phát triển. Hỗ trợ anh em thực hiện checklist công việc.",
    expand:'Mở rộng',
    detail:'Chi tiết',
    date:'Date',
    onlinePartner: 'Đối tác trực',
    offlinePartner: ' Nhân viên trực',
    slogan: 'Hãy trực theo một cách chuyên nghiệp nhất',
    phoneNumber:"0964854447",
    support:"Hỗ trợ :",
    back:"back",
    auth:'Xác thực',
    get:"Nhận",
    founder: "TungNgtg",
    optionPartner:"Chọn đối tượng",
    continous:"Tiếp tục",
    start:"Bắt đầu",
    inforPartner:"Thông tin người trực",
    requireAuth:"Vui lòng xác thực với mã OTP được gửi về điện thoại của bạn",
    whereLocation:"Hôm nay bạn trực ở đâu?"
}
export default wordApp;