const wordApp = {
    nameApp: 'TRỰC VĂN PHÒNG',
    username: 'Username',
    password: 'Password',
    remember: 'Remember Account',
    login: 'Đăng nhập',
    securityNetWork: 'Cài đặt mạng bảo mật',
    warningLevel:'Số lượng mức độ cảnh báo',
    correctationLevel: 'Tương quan mức độ cảnh báo',
    warningStatus: 'Trạng thái cảnh báo',
    refresh:'Làm mới',
    number:"Số lượng",
    status:"Trạng thái",
    description:"Mô tả",
    wait:"Chuyển xử lý",
    doing:'Đang xác minh',
    verified:"Đã xác minh",
    hight:"Cao",
    medium:"Trung Bình",
    low:"Thấp",
    function:"Chức năng",
    functions:{
        netWork:"Lớp mạng",
        server:"Lớp máy chủ",
        Application:"Lớp ứng dụng",
        endpoint:"Thiết bị đầu cuối"
    },
    expand:'Mở rộng',
    detail:'Chi tiết',
    unauthorizedAccess:'Truy cập trái phép',
    bandwidthWarning:'Cảnh báo băng thông',
    ddosWarning:'Cảnh báo Ddos',
    devicesStatus:'Trạng thái thiết bị',
    violateByTime:'Số lượng vi phạm theo thời gian',
    list:'Danh sách',
    infoWarning:'Thông tin cảnh báo',
    serverStatus:'Trạng thái máy chủ',
    scanPort:'Rà quyét cổng',
    violatePolicy:'Vi phạm chính sách',
    strangProcessDetected:'Phát hiện tiến trình lạ',
    disconnectWarning:'Cảnh báo mất kết nối',
    attackServiceWarning:'Cảnh báo tấn công dịch vụ',
    speedResponse:'Tốc độ phản hồi ứng dụng web',
    detailWaring:'Chi tiết cảnh báo',
    done:'Hoàn tất',
    name:"Name",
    sourceIp:"Source",
    destinationIp:"Destination",
    date:'Date',
    enterName:"Enter Name",
    enterSource:"Enter Source IP",
    enterDestination:"Enter Destination IP",
    disconnected:"Disconnected",
    connected:"Connected",
}
export default wordApp;